version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: run
    ports:
      - "5000:5000"
    restart: unless-stopped

networks:
  default:
    name: wrsnet
