version: "3.9"
services:
  api_getaway:
    build:
      dockerfile: docker/Dockerfile
      context: ../
    command: run
    ports:
      - "5000:5000"
    environment:
      - ENV=local
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

networks:
  default:
    name: wrsnet
